### ISSUE TITLE
Dataset and model

### ISSUE THREAD

**Issue by sntcristian** [mrpeerat/mReFinED#1]
Hi,
Thanks for the interesting project. Do you plan to upload the training data and models for Entity Linking?
Also, it would be nice to have a Jupyter Notebook showing how to do inference with this model :)

Best regards,
Cristian

**Comment by mrpeerat** [comment]
Hi! Thank you for your interest! 
the Amazon team decided not to release the data and model.
However, I'm building from scratch! Currently, the data is ready. But I don't have any free time for the training part.
For the inference, if the model is finished, I will release the notebook (the inference code is the same as the original ReFinED).

**Comment by sntcristian** [comment]
Thank you for the quick answer. 
Looking forward for the development of this project then!
